// Gatito dibujado a mano sobre la rejilla, siguiendo la hoja
// public/referencia/gatito-referencia.webp. No se extrae de la hoja: en
// ella los ojos, la boca y los bigotes miden menos que una celda y la
// extracción los rompía (ojos en barra, boca de 1 px). Aquí cada rasgo es
// un grupo de píxeles intencionado: ojos 2x2, rubor, hocico crema con boca
// en "ω", bigotes de 2 px y luz desde arriba a la izquierda.
//
// Todas las vistas miran a la izquierda; las de la derecha son su espejo.
// "sentado" es el gatito en el suelo; "tumbado", sobre la cabeza de la
// niña (misma cabeza, cuerpo recogido). La cabeza ocupa las filas 0-13.

export const KITTEN_SIT = {
  frente: [
    ".....kk..........kk.....",
    "....kYyk........kyyk....",
    "....kppyk......kyppk....",
    "...kYppykkkkkkkkyppyk...",
    "...kyppyYYYYyyyyyppyk...",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "..kyyykkyyyyyyyykkyyyk..",
    "kkkyyykkyyyyyyyykkyyykkk",
    "..kyppyyyyskksyyyyppyk..",
    "kkkOyyyyyskssksyyyyyOkkk",
    "..kOyyyyyyssssyyyyyyOk..",
    "...kOyyyyyyyyyyyyyyOk...",
    "....kOooyyyyyyyyooOk....",
    "....kyyyyyccccyyyyyk....",
    "...kyyyyyccccccyyyyyk...",
    "...kyyyyyccccccyyyyyk...",
    "...kOykyyyccccyyykyOk...",
    "...kOykyyyckkcyyykyOk...",
    "...kOkcckcckkcckcckOk...",
    "....kkkkkkk..kkkkkkk....",
  ],
  lado: [
    "......kk......kk...........",
    ".....kYyk....kyOk.....kkk..",
    ".....kppyk..kyOOk....kcYyk.",
    "....kYppyykkyyyyOk..kYyyyk.",
    "...kyyppyyyyYYyyyk..kyyyOk.",
    "..kyyyyyyyyyyyyyyyk.kkyyOk.",
    "..kyyyyyyyyyyyyyyyk...kyOk.",
    ".kyyyyyyyyyyyyyyyyyk..kyOk.",
    ".kyyykkyyyyyyyyyyyyk..kyOk.",
    "kkyyykkyyyyyyyyyyyyk..kyOk.",
    ".ksssyppyyyyyyyyyyOk..kyOk.",
    "kksssyyyyyyyyyyyyOOk..kyOk.",
    ".kksssyyyyyyyyyyOOk..kyyOk.",
    "..kkcsyyyyyyyyOOkkkkkyyOk..",
    "...kccsOyyyyOOkyyyyyyyOk...",
    "....kccyyOkkyyyyyyyyyOOk...",
    "....kcyyykyyyyyyyyyyOOok...",
    "....kyyyykyyyyyyyyyOOook...",
    "....kyyyykyyyyyyyyOOoook...",
    "....kcckckOOyyyyyOOoooOk...",
    "....kkkkkkkkkkkkkkkkkkk....",
  ],
  tresCuartos: [
    ".....kk.........kk..........",
    "....kYyk.......kyOk.....kkk.",
    "....kppyk.....kyOOk....kcYyk",
    "...kYppykkkkkkkyypOk..kYyyyk",
    "...kyppyYYYYyyyyyyOk..kyyyOk",
    "..kyyyyyyyyyyyyyyyyyk.kkyyOk",
    "..kyyyyyyyyyyyyyyyyyk...kyOk",
    "..kyyyyyyyyyyyyyyyyyk...kyOk",
    "..kyykkyyyyykkyyyyyyk...kyOk",
    "kkkyykkyyyyykkyyyyyyk...kyOk",
    "..kppyyyskksyyppyyyOk...kyOk",
    "kkkyyyyskssksyyyyyOOk..kyyOk",
    "..kOyyyyssssyyyyyyOOk..kyyOk",
    "...kOyyyyyyyyyyyyOOkkkkkyOk.",
    "....kOooyyyyyyyOOkyyyyyyyOk.",
    "....kyyccccyyyykyyyyyyyyOOk.",
    "...kyyccccyyyyykyyyyyyyOOok.",
    "...kyyyccyykyyyyyyyyyyOOook.",
    "...kOyyyyykyyyyyyyyyyOOoook.",
    "...kOykyyykyyyyyyyyOOoooOk..",
    "...kOkcckckcckOOyOOooOOOk...",
    "....kkkkkkkkkkkkkkkkkkkkk...",
  ],
  espalda: [
    ".....kk..........kk.....",
    "....kYyk........kyyk....",
    "....kYOyk......kyOyk....",
    "...kYyOykkkkkkkkyOyyk...",
    "...kyyyyYYYYyyyyyyyyk...",
    "..kyyyyyyyOOOOyyyyyyyk..",
    "..kyyyyyyyyOOyyyyyyyyk..",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "kkkyyyyyyyyyyyyyyyyyykkk",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "kkkOyyyyyyyyyyyyyyyyOkkk",
    "..kOyyyyyyyyyyyyyyyyOk..",
    "...kOyyyyyyyyyyyyyyOk...",
    "....kOOOOOOOOOOOOOOk....",
    "....kyyyyyyyyyyyyyyk....",
    "...kyyyyyyyyyyyyyyyyk...",
    "...kyyyyyyyyyyyyyyyyk...",
    "...kOyyyyyyyyyyyyyyOk...",
    "...kOOyyyyyyyyyyyyOOk...",
    "...kOOOooooooooooOOOk...",
    "....kkkkkkkkkkkkkkkk....",
  ],
  espaldaTresCuartos: [
    ".....kk.........kk..........",
    "....kYyk.......kyOk.....kkk.",
    "....kYOyk.....kyOOk....kcYyk",
    "...kYyOykkkkkkkyyOOk..kYyyyk",
    "...kyyyyYYYYyyyyyyOk..kyyyOk",
    "..kyyyyyyyyyyyyyyyyyk.kkyyOk",
    "..kyyyyyyyyyyyyyyyyyk...kyOk",
    "..kyyyyyyyyyyyyyyyyyk...kyOk",
    "..kyyyyyyyyyyyyyyyyyk...kyOk",
    "kkkyyyyyyyyyyyyyyyyyk...kyOk",
    "..kyyyyyyyyyyyyyyyyOk...kyOk",
    "kkkyyyyyyyyyyyyyyyOOk..kyyOk",
    "..kOyyyyyyyyyyyyyyOOk..kyyOk",
    "...kOyyyyyyyyyyyyOOkkkkkyOk.",
    "....kOOOOOOOOOOOkyyyyyyyOk..",
    "....kyyyyyyyyyyOyyyyyyyyOOk.",
    "...kyyyyyyyyyyykyyyyyyyOOok.",
    "...kyyyyyyyyOyyyyyyyyyOOook.",
    "...kOyyyyyyOyyyyyyyyyOOoook.",
    "...kOOyyyyOyyyyyyyyOOoooOk..",
    "...kOOOoooooooOOyOOooOOOk...",
    "....kkkkkkkkkkkkkkkkkkkkk...",
  ],
} as const;

export const KITTEN_LIE = {
  frente: [
    ".....kk..........kk.....",
    "....kYyk........kyyk....",
    "....kppyk......kyppk....",
    "...kYppykkkkkkkkyppyk...",
    "...kyppyYYYYyyyyyppyk...",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "..kyyykkyyyyyyyykkyyyk..",
    "kkkyyykkyyyyyyyykkyyykkk",
    "..kyppyyyyskksyyyyppyk..",
    "kkkOyyyyyskssksyyyyyOkkk",
    "..kOyyyyyyssssyyyyyyOk..",
    "...kOyyyyyyyyyyyyyyOk...",
    "....kOooyyyyyyyyooOk....",
    ".....kyyyyykkyyyyyk.....",
    ".....kckcck..kcckck.....",
    "......kkkk....kkkk......",
  ],
  lado: [
    "......kk......kk...........",
    ".....kYyk....kyOk.....kkk..",
    ".....kppyk..kyOOk....kcYyk.",
    "....kYppyykkyyyyOk..kYyyyk.",
    "...kyyppyyyyYYyyyk..kyyyOk.",
    "..kyyyyyyyyyyyyyyyk.kkyyOk.",
    "..kyyyyyyyyyyyyyyyk...kyOk.",
    ".kyyyyyyyyyyyyyyyyyk..kyOk.",
    ".kyyykkyyyyyyyyyyyyk..kyOk.",
    "kkyyykkyyyyyyyyyyyyk..kyOk.",
    ".ksssyppyyyyyyyyyyOk..kyOk.",
    "kksssyyyyyyyyyyyyOOk..kyOk.",
    ".kksssyyyyyyyyyyOOk..kyyOk.",
    "..kkcsyyyyyyyyOOkkkkkyyOk..",
    "....kyyyykyyyyyyyyOOoook...",
    "....kcckckOOyyyyyOOoooOk...",
    "....kkkkkkkkkkkkkkkkkkk....",
  ],
  tresCuartos: [
    ".....kk.........kk..........",
    "....kYyk.......kyOk.....kkk.",
    "....kppyk.....kyOOk....kcYyk",
    "...kYppykkkkkkkyypOk..kYyyyk",
    "...kyppyYYYYyyyyyyOk..kyyyOk",
    "..kyyyyyyyyyyyyyyyyyk.kkyyOk",
    "..kyyyyyyyyyyyyyyyyyk...kyOk",
    "..kyyyyyyyyyyyyyyyyyk...kyOk",
    "..kyykkyyyyykkyyyyyyk...kyOk",
    "kkkyykkyyyyykkyyyyyyk...kyOk",
    "..kppyyyskksyyppyyyOk...kyOk",
    "kkkyyyyskssksyyyyyOOk..kyyOk",
    "..kOyyyyssssyyyyyyOOk..kyyOk",
    "...kOyyyyyyyyyyyyOOkkkkkyOk.",
    "...kOykyyykyyyyyyyyOOoooOk..",
    "...kOkcckckcckOOyOOooOOOk...",
    "....kkkkkkkkkkkkkkkkkkkkk...",
  ],
  espalda: [
    ".....kk..........kk.....",
    "....kYyk........kyyk....",
    "....kYOyk......kyOyk....",
    "...kYyOykkkkkkkkyOyyk...",
    "...kyyyyYYYYyyyyyyyyk...",
    "..kyyyyyyyOOOOyyyyyyyk..",
    "..kyyyyyyyyOOyyyyyyyyk..",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "kkkyyyyyyyyyyyyyyyyyykkk",
    "..kyyyyyyyyyyyyyyyyyyk..",
    "kkkOyyyyyyyyyyyyyyyyOkkk",
    "..kOyyyyyyyyyyyyyyyyOk..",
    "...kOyyyyyyyyyyyyyyOk...",
    "...kOOyyyyyyyyyyyyOOk...",
    "...kOOOooooooooooOOOk...",
    "....kkkkkkkkkkkkkkkk....",
  ],
  espaldaTresCuartos: [
    ".....kk.........kk..........",
    "....kYyk.......kyOk.....kkk.",
    "....kYOyk.....kyOOk....kcYyk",
    "...kYyOykkkkkkkyyOOk..kYyyyk",
    "...kyyyyYYYYyyyyyyOk..kyyyOk",
    "..kyyyyyyyyyyyyyyyyyk.kkyyOk",
    "..kyyyyyyyyyyyyyyyyyk...kyOk",
    "..kyyyyyyyyyyyyyyyyyk...kyOk",
    "..kyyyyyyyyyyyyyyyyyk...kyOk",
    "kkkyyyyyyyyyyyyyyyyyk...kyOk",
    "..kyyyyyyyyyyyyyyyyOk...kyOk",
    "kkkyyyyyyyyyyyyyyyOOk..kyyOk",
    "..kOyyyyyyyyyyyyyyOOk..kyyOk",
    "...kOyyyyyyyyyyyyOOkkkkkyOk.",
    "...kOOyyyyOyyyyyyyyOOoooOk..",
    "...kOOOoooooooOOyOOooOOOk...",
    "....kkkkkkkkkkkkkkkkkkkkk...",
  ],
} as const;

// Cola de la vista de espalda en capa propia: se pinta encima del cuerpo y
// se mueve sin dejar hueco en el lomo.
export const KITTEN_BACK_TAIL: readonly string[] = [
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "..........kkkk..........",
  ".........kcYYyk.........",
  ".........kYyyyk.........",
  ".........kYyyOk.........",
  ".........kyyyOk.........",
  ".........kyyOOk.........",
  "..........kkkk..........",
];
