// ARCHIVO GENERADO por scripts/extract-nina-gatita.ts: no editar a mano.
// Cada sprite es la rejilla lógica extraída de una figura de la hoja de
// referencia (public/referencia/nina-gatita-referencia.webp).
// meanDeltaE: ΔE CIE76 medio entre el color final de cada celda y los
// píxeles reales de su interior. Por debajo de ~2 no se distingue; los
// valores de 5-8 vienen sobre todo del antialiasado y los degradados que la
// hoja tiene dentro de cada "píxel".
import type { ReferenceSprite } from "./types";

export const REFERENCE_SPRITES = {
  abajoIzquierda: {
    label: "Abajo-Izquierda",
    faces: "abajo-izquierda",
    box: [83, 184, 284, 432],
    pitch: [4.49, 4.46],
    meanDeltaE: 7.61,
    rows: [
      "........................kkkk.................",
      "..........kk...........keYYYk................",
      ".........kOOkk...kkkk..kYccyOk...............",
      ".........KooOdkkkYOOKk.kYyyyOk...............",
      ".........KOyyyyyySSoSd.dkeyOOk...............",
      "........kYyyyyyyyyooLd..kLOOok...............",
      "........kyyyyyyyyyyOoLK.kLOook...............",
      ".......kYYYyyyyyyyyyyoHkooook................",
      ".......kOkkyyykkyyyyyooSiooi.................",
      "....kkkdicsRssKOyyyyyooOLKkkk..kkkk..........",
      "...khHHiKsSSssscYYyyooyyokDDkkkHhhkk.........",
      "...kHhHhhKdswssscOOoOOyookdKhhhhHhhk.........",
      "...kHphHhkcoLLsskeYOOoooKDiHHHhppHhk.........",
      "...kipphhkYYOOkkcYYyOiBKhHBHHHppphhkd........",
      "...kDppHhkGcLKhkcYYyOKDhHHBBipppPhhKk........",
      "....kPpedHkkdHBkkYYykhHHhhHHpppPPhhKk........",
      "....kPPiBBBBBBBBdkkkhHBBHHdppPPPPhhKk........",
      "....kBiBBBBBBBBBBBBBBBBBBBBdPPPPShhKDk.......",
      "....kdLLBBBHBBBBBBBBBBBBBBBBhPPPRHhkDk.......",
      "...KDBLLLBBHBBBBBBBBBBBBBBBLBhPPihidhKd......",
      ".kkDdBBLBLHLLLBBBBBBBBLHLLLLBHiPihdhhhk......",
      ".khDiBBBBBhBLLLBBBBhLLLHBBBBBBDhhdDBBHDkK....",
      ".khKBBBBBBBBBBBBBBBhBBBBBBBBBBhhHhHBBBHDk....",
      "..kKBBBhBHiBBBBBBBHdHBBBBBBBBBBdHBBHHHhhk....",
      "..kKBBBhHiSHBBBBBhdSdHBBHhBBBBBDHBBHhhDk.....",
      "kkHhDBBDDBShBBBBBhiSSdHHhDBBBBBBDHBHHdk......",
      "kHBBdHBdDeSihBBBHDLSPSdhhDBBBBBBBiHBBHKk.....",
      "kHBHDHHKkkkSihBHHDSPkkkDDdBBBBHBBiBBBBHk.....",
      ".KHHhdhKkkkkSBdhhdSkkkkkhKBBBBiHdhHBBBhhk....",
      ".khhDDKdkGkkSSSdddSwkkkGkkBBBHdKDhHHBBHhk....",
      "..kkKhdKkwkksssSSPsKkkkGkkBBHhKDhhiHBHhk.....",
      "...KKhhKdwdKsssssssKKkkwkKhhhKDhHHhDDDKk.....",
      "...kDhhKDwHdsssssssKhikwSdddKDDhHHDDDDkkkk...",
      "...kKDDkdPSHsssssssdHHdsSShHyOkDhhDdkkBBBBk..",
      ".....kkdkSPssssssssssSPSSSiyYykDhDDkdBBLBBHk.",
      ".......kdKdPsssSsssssPSSSdhKykDDDDKKBBLLLBBhk",
      "........kKKkkSssssssPSSKkkDKkDDKdkkHBBBLBBBHk",
      "..........kRRRKKHLLLdkkRRKdDDDk...kHBBLBBBHHk",
      ".........KRrrRRRwPGGRRRRRRkddk...khhHBBBBHhHk",
      "........kDrrrirrRiiRrrrrrrKkkk..kDhHBBBBBhkk.",
      "........kPRrihrrrrrrrrrrrrRkDKkkDhhHBBBBHk...",
      "........kkkRKRrrrrrrrrrrrrrkDddDhhHHHHHHhD...",
      "...........kkKprrrrrrrkrrrrRkDDDDhhhHHhhDk...",
      "..........kkgggKRrrrrRKrrrrikDDDDDDhhDDDk....",
      "...........kggggkkkkkkKdRRRSkKKDDDDDDdkk.....",
      "............kgggggggggkssssSkddkkkkkk........",
      ".............kkkgggggggkPsSkkkk..............",
      "..............kPkkkkkkkkkkkkk................",
      ".............kkRGGGkkSSSegk..................",
      ".............kGprrRkgwwGGgk..................",
      ".............kkwwekkRrrPRDk..................",
      "...............kkkkkwwwrpeK..................",
      "...................kkwwGkk...................",
      "....................kkkk.....................",
    ],
  },
  abajo: {
    label: "Abajo",
    faces: "abajo",
    box: [378, 184, 563, 432],
    pitch: [4.13, 4.31],
    meanDeltaE: 8.19,
    rows: [
      "..............................Kkkk...........",
      "................kK...........kcccYK..........",
      "..............kkOOk.....kkK.kcYcYYOk.........",
      "..............kSoookkkkkOOikkYYyyyok.........",
      "..............kSooOyyyLOoookkkkYyyok.........",
      "..............kSOyyyyyyyOSok..kOOOok.........",
      ".............kOOyyyyyyyyyyokkkkOOok..........",
      "............KkcyyyyyyyyyyyOBkkooook..........",
      "...........kLoOycYyyyyYyyyyLKoooSk...........",
      "...........kLLOYkkYYYYkkyyOoBioKk............",
      ".....kkkkk..dKOykkRssskkyyOookkk..kkkkk......",
      "....kdhhhDkkkkkcsspssssYYOoOoKkkkkhhhhKk.....",
      "....kDHHHHHhKkkkisssssccoooOoKkhhHHhhHdk.....",
      "....khHHHHHHhdkGOoLssscBOOoooKhHHBHhHhhk.....",
      "....khHppHHHHdhYcyOkkkkcYYOdkhHBBHHprhhk.....",
      "....khHPppiHHiKYYyLkhhkccyykhhHBHpppPhhk.....",
      "....khHPpppihhdKKKkhHhKkYykhhhidpppPPhhk.....",
      "....khHPPSpSihHHHHHBHHHhkkhHHHHdpppPPhhk.....",
      "....khhPPPPiBBBBBBBBBBBBBBBBBBBBHPPPPhhk.....",
      "....kdiPPPhBBBBBBBBBBBBBBBBBBBBBBhPPPhdk.....",
      "....kDDePHLBBBBBBBHBBBBBBBBBHBBBLLHPPhKDk....",
      "...kBidPiLLLLLBBBHHBBBBBBBBBBHBLLLBiPKDhkK...",
      "kkKBBHidBBLLLBLLBHBLBBBBBBBBLLHLLLBhDdhBHhkk.",
      "khBBBHHdBBBLBLLLhhLLLBLLBHBLLLHBLBBBdhHBBHhk.",
      "kHBBBHdBBBBBHBBBhhLBLBBBBHHBBBHhBBBBhihBHBhk.",
      ".khHhDdBBBBHBBBBhhBBBBBBBhiBBBHhBBBBBdDHHHk..",
      "..kkhdBBBBBhHBHhShBBBBBBBiSdHHHhhBBBBhdhHk...",
      "..kBBdBBBBBDHHiSSihBBBBBHhSSdhHhiBBBBBiHHhk..",
      ".kHBBiBBBBBDDiSSsPiHBBBBiSPSSiDhiBBBBBBhBBhk.",
      ".kHBBHiiBBBKHSkkkkSdHBBHiSkkkkkddBBBDBdHBHhk.",
      ".kDHHHhdHBBKdkkkkkkSdHHHiSkkkkkdkBBHddhhHhk..",
      "..kDhhidDHBKkGkwkkkSSiihiswkkkGkkBHhdDDhDdk..",
      "...kdiHDKhhKkGkkkkksSPSSsskkkkGkKBhdDHHDkk...",
      "...dKHHhddddKwkkKKksssssssKKKkwLiDKhiHHDK....",
      "...KDhhdOBHKSwkKhhKsssssssDihKwSdiLYdhhDd....",
      "...khDDKYYBKSPsiHHhssssssshhHhsSdHBYdhDKkk...",
      "....kdDdKyBKSSSPPGssssssssGSSPSLOOdKDKkhhHk..",
      "......kDKKhhKSSSsssssSSssssPSSSKyOKDKhBBBBBk.",
      "......kDDdihKkkSSSsssssssssSKKkdKKddhBBLLLBhk",
      "......kkdDDDddKkkkKKLLLLRkkkkKDDDDdKhBBBLLBBk",
      "........kDdDDdKRRRRdPSSPdRRRRkkDDDKKhBHBLBBBk",
      ".........kddKHRrrRRriGwdRRRrRRkkdKKDHHBBBBBBk",
      "..........dkRrrrrHrrrRRrrrirrrRkKDDhHBBBBBBHk",
      "..........kDrrrrHrrrrrrrrrirrrriKDDhHBBBBBHk.",
      "..........kPRrrrKrrrrrrrrrrKrrRSdDDhHHHBHHhk.",
      "..........ksPPSRKirrrrrrrrRkRRPPddDDhhhhhhk..",
      "...........ksPPkggkkkkkkkkggkssdKDDDDDDDkk...",
      "............kkkggggggggggggggkkkDKkkkkkk.....",
      "..............kkgggggggggkggkkk..............",
      "...............kkkkggggggkkkKk...............",
      "...............kkGSkkkkKkhSkk................",
      "................kGSSSkkSSSSk.................",
      "...............kkGwPwkkGwPGkk................",
      "...............keRrrPkeprrrek................",
      "...............kpRwwrdeRwwrek................",
      "................kwwwGkkwwwGk.................",
      ".................kkkkkkkkkk..................",
    ],
  },
  abajoDerecha: {
    label: "Abajo-Derecha",
    faces: "abajo-derecha",
    box: [649, 184, 841, 432],
    pitch: [4.49, 4.27],
    meanDeltaE: 7.52,
    rows: [
      "...............kkkk........................",
      "..............kYYYck..........kk...........",
      ".............kccYYYK..kkK....koSk..........",
      ".............kYYyyyK.kLOdkkkkoook..........",
      ".............kyyyyYd.koooLYyyyoLk..........",
      ".............kOOOOk..koSoyyyyyyok..........",
      ".............kOOook.KKoOyyyyyyyyLk.........",
      ".............kOoookkkOoyyyyyyyyyBk.........",
      "..............kooooSkOyyyyyyyykYOLk........",
      "...............koooooOyyykkyyykyOLK........",
      ".........kkkk..kkkkooOyyyYkcRccYOk..kkkk...",
      "........KKhhHkkdDDkoYoOyYYsspssskkkkHHhhk..",
      "........kDHHHHhDDDkOOOOLOcwwssskDDhhHHHhk..",
      "........khHpBhHHDdDiOOOYiHSSLLOOkHHhhiphk..",
      "........khHppiHHHiDKSOYYckkkKOYykHHHhrphk..",
      "........khHppphHHhdDkyYYckDDkcYckHHHrpphk..",
      "........khhPPppHHhdHikccLkHHhKdkDhHpppPhk..",
      "........kHhPPPpPiDHBBHKkkHBBBHhhHippPPPDk..",
      "........khHPPPPihBBBBBBBBBBBBBBBBBhiPPPk...",
      ".......kKhhPPPhBBBBBBBBBBBBBBBBBBBBBdPhk...",
      ".......kdhHHPPHLBBBBBBBBBBBBHBBBBBLLihKk...",
      "......khDhHhPhLLLBBBBBBBBBBBBHBBHLLLBdKK.kk",
      ".....KKHHdhhHHBLLLBBBBBBBBBBLHBLHLLBBHdHKDk",
      "...kkDhBBdihiBBBLLHLLBhBLBLLLHBLBHBBBHdHHhk",
      "...khHHBHHHhiBBBBBHBLHhBLBLLBhBBBiHBBBKhHhk",
      "...khHHHhBHhhBBBBBHBBHhBBBBBBhHBBhHBBBHhhk.",
      "....khhhiBBDBBBBBhBBHdiBBBBBBhiBBhhBBBBdk..",
      ".....kdhBHHdBBBBhDHHhShHBBBBBiSiBHiBBBBk...",
      "....kdHBBHdBBBBBiDHDSSiHBBBBhdSdhhdBBBHdk..",
      "...kDHBBBBBBBBBBhDDHSSShBBBBdSSkdDKBBBihk..",
      "...kHBBBBiBBHBBBdDSkkkSDHBBhdSkkkkkBBHihk..",
      "...kHHBBBHiHhBBBdKKkkkkDHHhKSkkkkkKBBhdd...",
      "....kHHHHhDdKHBBdkGkkwkSddLSSwkkGkhBDKDk...",
      ".....KhhhhHidDhBdkGkkkkPSSSsskkkwkhDKdk....",
      "......kkhhHHikhHDKwkKKksssssskdKwkddDk.....",
      "......kDDhHHDLKddSwKiiKssssssKhHwkdDDDk....",
      ".......kdDhhkcohiSsiHHdsssssssHPSkDDDDk....",
      "........KDDDkYOBdSSPSessssssssSSkDDDkk.....",
      "..kkkkK..kDDDLyDiKSSPssssLLsssPKdDDk.......",
      ".kBBBBdk.kkDDKKhhkkBSsssssssSKkkDdk........",
      "kHBLLBBhk..kkDDDkDRikkLLLLKkRRkD...........",
      "kBLLBBBhk....kdkirrRRRiwPdRRRRRk...........",
      "kBBLBBHhDk...KkKrrrrrrrDeRrRRrrDk..........",
      "kBBBBBHHHDKkkDKRrrrrRrrrRrrrdrrSk..........",
      "khHBBBBBHhDDDDKrrrrrRrrrrrrrkHSSk..........",
      ".kHBBBBHHhDDDkRrrrrirrrrrrrHkkPk...........",
      ".dhHHHBHhhDDDkiRrrrKRrrrrhKggkk............",
      "..kHHhhhhDDDDksSRRigkkkkkggggk.............",
      "...kkdDDDDDDKkPsPSSkggggggggk..............",
      ".....KkkkkkkkkkPSSkggggggkkk...............",
      "..............kkkkekkkkkkSSk...............",
      "................kkSSSSkeGGek...............",
      "................keGwwekeRrRk...............",
      "................keprrRkepwk................",
      "................keprwrekwwwK...............",
      ".................kkwwwK.kkk................",
      "..................kkkk.....................",
    ],
  },
  izquierdaFila1: {
    label: "Izquierda",
    faces: "derecha",
    box: [915, 182, 1084, 432],
    pitch: [4.59, 4.34],
    meanDeltaE: 6.93,
    rows: [
      "...........kkkk......................",
      "..........kccccK.....................",
      "..........kYcccOk...kk...............",
      ".........kyYYYYOk..kook..............",
      ".........kyyyyYOk.kOOookkkkkk........",
      ".........kyyyYdd.kOyooOyyByok........",
      ".........kOyOOk.kOyyyyyyyyook........",
      ".........kOOoOkkeOyyyyyyyyyok........",
      "..........kooookOyyyyyyyyyyok........",
      "...........koodSoyyyyykkYYYkLk.......",
      "..........kkkkkooyyyyyYyspsLSk.......",
      ".........khhHikKOoOyyYcssRRSkKkk.....",
      "........kdHHHHHhkooooycsswskSSdk.....",
      "........kiHpRHhhhkoooOHKkkkLSPddk..k.",
      "........kHHpppphhhKoyyYYkDDkkKKDhkkk.",
      ".......kkHHpppppihKkYccckhHBHDdiDhkk.",
      "....kK.kkhHPPPpppdddKYcKKHBBBHhdhhDk.",
      "....kDkkkhHPPPPPPKhHdkkKBBBBBBHHdDk..",
      "....khhhkhHPPPPPihHBBBBBBBBBBBBLBk...",
      "....kDhhkHHPPPPDBBBBBBBBBBBBBLLLLBk..",
      ".....KhHDhHHPPPhLLBBBBBBBBBBLBLLBHDK.",
      ".kk..KHHhDBHPPiBLLLBBBBBBhBLLBBBBBHk.",
      ".kkkkHHBHdBHihhBBLLLBBLLBhBLBBHBBBBk.",
      ".khHHHHBBdHHHhBBBBLLhBLLBdBBBBhHBBHhk",
      ".kHHBHHBBBHHhhBBBBBBhBBBBdBBBBHiBBHhk",
      ".KDHBhBBBBBHDBBBBBBBhBBBHdhBBBHiBBHhk",
      "..khhhBBBBBBDBBBBBBHhBBBiSdHBBHdBBHhk",
      "...kKHBBBBHhBBBBBBBHhBBiSSHhBBHdhHDDk",
      "...kHBBBBHHiBBBBBBBDhHhBSSLhBHKdhhkk.",
      "..khBBBBBHiBBBBBBBBdhiLSPShDhDKDhhk..",
      ".kdBBBBBBiBBBBHBBBBdhkkkkPhDDkDhDk...",
      ".kHBBBBBBHiBHHhHBBBKSkkkkSPKkDDDk....",
      ".khHHBBBHBDddDDHBBBKkGkkksskDdKk.....",
      "..khhBBHHBHhDddhHBHLkGkkksskdDdk.....",
      "...kKHHhhBHHhDkkhhHdPwidKssPkDDd.....",
      "...khHhDDHHHhKLiKDDHPwhhhssskDDDk....",
      "...khhhDDhhhkYcYHdSSSssssssskKkk.....",
      "....kDDddhhDkYcyoDSSSPsssssSk........",
      ".....kkkDDDDDkyydDiSSPPsssSk.........",
      ".......kkKDDDDKKdDkLSPssskk..........",
      "...kkk...kkkDDDDkRRihkkkkk...........",
      "..kBBBk....DkddkRrrRRPekk............",
      ".kBLLBhk....dkkhrrrrrRRRkd...........",
      "kHBLLBBhk..kKDKrrrrRrrrrrk...........",
      "kBLLBBBhk..kDKRrrrrrRrrrrk...........",
      "kBBBBBHhDdkDDkprrrrKrrrpKgk..........",
      "kBBBBBHHDdDDDkhRrrrKKKKkggk..........",
      "kHBBBBHHHhhDDksSRRikgggggk...........",
      ".kBBBBHHHhhDDkssssPkggggkK...........",
      ".khHHHHhhhDDdkkPsPkgggkkk............",
      "..kDhhhhDhDDkkkkkKKkkkkk.............",
      "...kkDDDDDkk....keSSSek..............",
      ".....kkkkk......kGwweiKk.............",
      "................kRwrrrpk.............",
      "................kRrrwwwk.............",
      "................kGGwwGk..............",
      ".................kkkkk...............",
    ],
  },
  derecha: {
    label: "Derecha",
    faces: "derecha",
    box: [31, 517, 207, 782],
    pitch: [4.78, 4.4],
    meanDeltaE: 7.18,
    rows: [
      "......................kk.............",
      "....................kkOOk............",
      "................kkkkhoookk...........",
      "...............kOOOiKOyyydk..........",
      "..........kkk..koSSOyyyyyyYk.........",
      ".........kccck.kooSyyyyyyyyk.........",
      "........kYcYykkhoOyyyyyyyyOk.........",
      "........kYYYYkkoOyyyyyykyycOkkk......",
      "........kyyyk.koyyyyyyckYspSkDDk.....",
      "........kOyOk.koyyyyyyyYsRpkhhhk.....",
      "........koOOokkoOOyyyyccsskhHHDk.....",
      ".........kOOookkkoOOOOOSckKddhhk.....",
      "..........kooekHhkkLooOyYkKhhKkk.....",
      "...........kkkhHhhhhKkOYcykHBBBHkk...",
      "...........khkHHpiHhhdkyYLhBBBBHBBd..",
      "..........khhkHHpppHhhKddkBBBBBBLLk..",
      "..........DhhkHHppppRhhHBBBBBBBBLLHk.",
      ".........kHBHkHHSpPPPiBBBBBBBBBLLBBk.",
      "........KdHBHkHHPPPPHBBBBBBBBhLLLBBhk",
      ".....kkkdhHBHKHHPPPeHBLBBBBBLHHBBBHHk",
      ".....khhhhBBHKhHpPPHBLLLLBBLBHDBBBhHk",
      ".....khHHhBBBDiHhPiHBBBLBBhBBHDBBBhHk",
      "......kDhHHBBhDHHhHHBBBBBBhBBHdHBBhhk",
      "......kkhBHBBHdHHHHBBBBBBBhBBdLhBBhd.",
      ".....kkHBBBBBBhhBHDBBBBBBhhBhiSKHBhk.",
      "...kkDHBBBBBBhBBBHdBBBBBBhhBiSSKhhDd.",
      "...kHBBBBBBBBhBBBhiBBBBBBdhhDHSKhhK..",
      "...kHBBBhBBBHHBBBiBBBBBBBdhkkkBKhD...",
      "...khHHhBBBBhBBBBiLBBBBBBKKGkkPkDk...",
      "....kDDhBBBBiBBBBhhhhBBBHKSwkkskk....",
      ".....KKBBBBHdBBBHhhKdhHBHKPwddsPk....",
      ".....kHBBBBhdhBBhhKHdKhhddswhsssk....",
      ".....kHHBBHhDdHhhkLccLDdLPssssssk....",
      ".....kDhhhhDDDddDkcYYyDDSSPssssed....",
      "......kDhhhDDDDdDkGyYyDDSSSsssSk.....",
      ".......kdDDDdDDDDDkKOkDDdSSssLk......",
      "........KkDDddDDDDdKkkkkLHKkkk.......",
      "...kkkK...kkkddDDDdkkRRRRPDk.........",
      "..kBBBhK.....kkDDDdKRrrRRRRK.........",
      ".dHBBBBdd......kdKkDrrrrRrrK.........",
      ".kBLBBBHk.......kKiRrrrrrrrRk........",
      "kHLLLBBBk......kiRKRrrrrdrrrk........",
      "kBLLLBBHk.....KkRRKrrrrrdrrRk........",
      "kBBLBBHHK.....KKiDRrrrrrKRrdk........",
      "kBBBBBHHhk...kdggkRrrrrpkKKggk.......",
      "kHBBBBBHhhKkkdkggKDHRRBPskgggk.......",
      "khHBBBBBHHDDDDkgggkPPsssskgggk.......",
      ".khHHBBBHHHhhDDkggkPSsssSkggk........",
      "..KHHHBBHHHhDDDKkggkKSsSkggk.........",
      "..kdhhHHhhhDDDdk.kkkkKkkKkk..........",
      "...kKDhhhhDDDDk...kSSSSSSkk..........",
      ".....kkDDDDDDk....kgPPPwkkk..........",
      ".......kkkkkk....kkwwwwiiKk..........",
      ".......kkkkkk....kggGwGRpwkk.........",
      ".................kHRRRrwpwwk.........",
      ".................keRRrrrwwwk.........",
      "..................kGGGGwwwkk.........",
      "...................kkkkkkkk..........",
    ],
  },
  arribaIzquierda: {
    label: "Arriba-Izquierda",
    faces: "abajo-derecha",
    box: [267, 517, 445, 782],
    pitch: [4.37, 4.36],
    meanDeltaE: 7.21,
    rows: [
      "............kkkk..........kk.............",
      "...........KccccKk.......kok.............",
      "..........kYYYccYkkk....KOoLk............",
      "..........kyyYyYKkOOkkkkOOoSk............",
      "..........kyyyykKkoSooyyyyyok............",
      "..........kooook.kooyyyyyyyyyk...........",
      "..........kooook.kOyyyyyyyyyyk...........",
      "...........kSoooKLyyyyyyyyyYyokD.........",
      "............kLookoyyykkyyyYkYooK.........",
      ".............DkkLLOyyYkcsRccyoKd.........",
      ".......kkkkkkkDkoooyyYcspPssOkkD.kkkk....",
      "......kdHHHHhdkkOooSLOsswsPBDkdkkHHHhK...",
      "......kHHHBBHHhikoyYYKkkkdoYYcDHHHHHHk...",
      "......kHHpphHHHDdkycYKDDDkYYyKHHHHRphk...",
      "......khHpppHHhhhDKcOKDhhKKKKKhHHBpphk...",
      "......khhPpppRhdHBhkkhBBHhhiDhiHHrpPHk...",
      "......khhPPPPhiBBBBBBBBBBBBBBBHdipPPhk...",
      "......khhPPPHBBBBBBBBBBBBBBBBBBBBBPPhk...",
      "......KKDPPLLLBBBBBBBBBBBBBBBBBBLLHekk...",
      ".....khKhhBLLLLBLBHBBBBBBBBBBBBLLLBdDK...",
      "....kDhhDKBBBLBLLLhLLLBLLBhBLLBHLBBDDDk..",
      ".kkKDHBhdBBBBBBBBBDLLLBLBBhHLBHhBBBHhHhkk",
      ".khBBBBhdBBBBBBBBHdBBBBBBBihBBBiBBBHHHHhk",
      ".khBBBHDiBBBBBBBBhdBBBBBBHiihBBhiBBBdHHhk",
      "..KhBBHKBBBBBHHBHiLHBBBBBHiSKhhhDBBBdhDk.",
      "..kKDhhdBBBBBiHHiSLiBBBBHiSSSdhhdBBBiKdk.",
      "....kkHiBBBBBiDdSsSdhBBBhDSPPPDDdBBBBdk..",
      "....kHBiBHBBBDDSkkSSdHHHHLSKkkKBKBBiBDK..",
      "...kHBBHddHBBDkkkkkkSihHhSKkkkkKkHBiiBhk.",
      "..khBBBHhKhBBikGkwkkSSDiiSKwkkkkkHHdHBHDk",
      "..kHHHHHHDKDHhkGkkkksPPPPPkkkkwkdhdhHBHDk",
      "...kDhHhhhKKKKSwkKDksssssskKdkwSKddDhhhk.",
      "....kkDihKOLDdSwkHHhssssssdHBDwSKDodDKk..",
      "......kDhkYyOdSSSHhssssssssHHPPSOLBdKk...",
      "......khhddyOiBSSPssssssssssPSSByOKDDk...",
      "......kDDDKKOhkSSPsssSSLssssPSKKyLDDDk...",
      ".......kdDddKKDKKSsssssssssPLKKdkKDDk....",
      "...kkk...kdDDDDDkkkkiLLLLKkkkkDDddDk.....",
      ".kdHHHkk..kkdDdkiRRRKsSPSDRRRkdDddk......",
      ".kHBBBhk....kkKkrrRRRisDRRRRrRkdkk.......",
      "kHBLLBBHk....DKrrrirrrrrrrrRrrRk.........",
      "kHLLLLBBhk..kirrrrirrrrrrrrrrrrRk........",
      "kBBLBBBHhk.kkRrrrirrrrrrrrrRRrrrdk.......",
      "kBBBBBBhhDkkSSRrrKirrrrrrrRiDrRRSk.......",
      "khBBBBBHHhDksssLdggkkkkkkKggkRssSk.......",
      ".kHBBBBHHHDDkHsLkggggggggggggkPPk........",
      ".khHBBHHHhDDDkkkgggggggggggggkkk.........",
      "..khhhHHhDDDDDDdkkggggggggkgkk...........",
      "...kDDhhDDDDDDDDkkkkkkkkkkkkk............",
      "....kkdhDDDDDDkkkkSSSekkSSSSk............",
      "......kkkkkkkkk..kPsGggkPwwGk............",
      "................kkwwwekkwwwwkk...........",
      "................kGprpekKwrRwek...........",
      "................kprrrRkerrrrpk...........",
      "................kRwwPpkepwwePk...........",
      "................kwwwwkkkwwwwkk...........",
      ".................kkkkk..kkkkk............",
    ],
  },
  arriba: {
    label: "Arriba",
    faces: "arriba",
    box: [503, 517, 689, 782],
    pitch: [4.56, 4.18],
    meanDeltaE: 5.49,
    rows: [
      "..............kk......kk.................",
      ".............kook....kook................",
      ".............kooOkkkkOOok..kkkk..........",
      "............kLoyyyyyyyOok.kLccck.........",
      "............kOyyyyyyyyyok.kcccYOk........",
      "............kyyyyyyyyyyyk.kYYYyok........",
      "...........kSyyyyyyyyyyyokkkyyyok........",
      "...........kOyyyyyyyOOyyOkekyyyok........",
      "...........kLyyyyyyyyyyOokkOOOoLk........",
      "......kk....kOOyyyyyyyyookOOOOok.........",
      "......kkd...KKOyyyyyyyooKBOOooLkk........",
      ".....kHHHkkkekkoOyyyOooKkooooKkkk........",
      ".....khHHHhkkKYYOooooYyOkkkkkDhHdk.......",
      ".....kBHBBHHkYYYOiodYYYokkhHHBHHhk.......",
      ".....kBBBBBHhkYykkkkiYOkdhHBBBBBhk.......",
      ".....kBBBBBHhDkkKhhhkkkdhhBBBBBBhk.......",
      ".....kHBBBHHHHHHHHHHHHhHhHHBBBBHhk.......",
      ".....kHBBHHHHBBBBBBBBBBBBBHBBBBHhk.......",
      "....KkhBBHBBBBBBBBBBBBBBBBBHBBBHhk.......",
      "....kdhHHLBBBBBBBBBBBBBBBBBBBHHhDdk......",
      "....kDDiLLBBBBBBBBBBBBBBBBBBLHhhKDK......",
      "...kDDDBLLLBBBBBBBBBBBBBBBBLLLhhKhk......",
      "...khhDBLLLLBBBBBBBBBBBBBBLLLBBdhhhkk....",
      ".kkhHhHBBLLBLLBBBBBBBBBBLBLLBBBdDHhDDk...",
      "KhHHHhHBBBBBLLLBLBBLBBBLLBBBBBBHdHHHhk...",
      "kHHHHiBBBBBBBBBBLBBLBBBLBBBBBBBBDHHHDk...",
      "khHHDBBBBHHBBBBBBBBBBBBBBBBBBBBBihHhDk...",
      ".khhdBBBBHBBBBBBBBBBBBBBBBBHBBBBHdhDk....",
      "..kkhhHBHhBBBBBBBBBBBBBBBBBhHBBHHiKk.....",
      "..dkBBhHHhBBBBBBBBBBBBBBBBBhhHHhDHhk.....",
      ".kKHBBHhdBBBBBBBBBBBBBBBBBBHdhhHBBHik....",
      "kkHBBBBhhBBBBBBBBBBBBBBBBBBBDhHBBBBHDk...",
      "kHHBBBBDBBBBBBBBHBBBBBBBBBBBBDHBBBBHhk...",
      "kHHBBBHDBBBBBBBBHBBBBBBBBBBBBDDhBBBHhk...",
      ".khhhhDBBBBBBBBBBBBBBBBBBBBBBBDDhhHHk....",
      "..kkhDdBBBHBBBBBHBBBBBBBBBBBBBDDddKk.....",
      "....kKhdBBhHBBBHhBBBBhHBBBHhHHDDDdk......",
      "...kkhHDhhDHBBBHDHBBHhHHBHhDhDDDhhk......",
      "...kDhhDDDdhHHHhDhHHhDhHHHhdDDDDDhK......",
      "...kkDDDDDdDhHHDKhHhhDDhHhDKDDDDDDk......",
      ".....kkddDDKDDDDkhhhDdDDDDKDDkkdkk.......",
      ".......kkDDDkDDDkDDDdKKDDkDdk..kk........",
      ".........kKKRkKKRKDdKDRkkRkk.............",
      ".........kkKRRRRRRiiRRRRRRRk.......kkkk..",
      ".........kRRRRRRrrRRRRRRRRRRk.....kBBBBk.",
      ".........drrrRRrrrrrrrrriRRRDK...kHBLBBHk",
      "........kPRrrirrrrrrrrrrRiRRSk...kBLLLBBk",
      "........KsPHRKRrrrrrrrrrRKRSSk..KDBBLLBBk",
      "........kPSSdkghprrrrrRdKkKSgK..kHBBBLBBk",
      ".........kSSkgggkkKkkkkgggkkkkkkhHBBBBBHk",
      "..........kkKggggggggggggggKhhhhHBBBBBHhk",
      "...........kgggggggggggggggKihhHHBBBBBHk.",
      "............kgggggggggggggkDDhhHHHHHHHhd.",
      ".............kkkgggggggkkKDDDhhhHHhhhDk..",
      ".............kkSKkkkkkkSkkDDDhDDDDDDdk...",
      "..............kSSSSkkSSSkkkkDDDDDDDkk....",
      "..............kGwGGkkGwwkk.kkkkkkkk......",
      "..............kkwwwkkwwwkk...............",
      "..............kprrrkeprpek...............",
      "..............krwprkerwrek...............",
      "..............kGwwgkkGwwk................",
      "...............kkkkkkkkk.................",
    ],
  },
  arribaDerecha: {
    label: "Arriba-Derecha",
    faces: "arriba-derecha",
    box: [745, 517, 919, 782],
    pitch: [4.49, 4.14],
    meanDeltaE: 6.02,
    rows: [
      "..........................kkk..........",
      "................kk.......kYYYK.........",
      "...............kook..kkkkYYYYOk........",
      "...............koookkOoSKYyyyOk........",
      "..............kyyyyyyOoSkhKyOOk........",
      ".............KLyyyyyyyoSkekOOok........",
      ".............kyyyyyyyyySkkKOOok........",
      "...........DdKyyyyyyyyyOkhoook.........",
      "...........kooyyyyyyyyyOKooooK.........",
      "...........kooyyyyyOOyyOKLook..........",
      "............koyyyyyyyyyooKKk...........",
      "............kkOyyyyyyyOookkk.kkkkkk....",
      "......kkkkddkkkooyyyyoLookkkkKhhhhKk...",
      ".....kDHHHidkkYyyooooyyOkkkhHBBBBHdk...",
      ".....kHBBBHHhkYYyOSkycYOkKhHBBBBBHdk...",
      ".....kHBBBBBHDkOyKKkGYyOdhHBBBBBBHdk...",
      ".....kHBBBBBHhdkkDhdkcckhHHBBBBBBhdk...",
      ".....kHBBBBHhHBBBBBHhKkhHHHHBBBBBhdk...",
      ".....khBBBHHBBBBBBBBBBBBBBBBHBBBBhdk...",
      ".....khBBHBBBBBBBBBBBBBBBBBBBhHHhhdk...",
      ".....kDHHLBBBBBBBBBBBBBBBBBBLLhHhhk....",
      "...KKDKhBLLBBBBBBBBBBBBBBBBLLLhHhhk....",
      "...kdhdiBLLLBBBBBBBBBBBBBBLLLBBDDKDk...",
      "..kDHhdBBBLLLLBBBBBBBBBBLBBLBBBiKDhDkkk",
      "kkdHHhdBBBBBLLLBLLBLBBLLLLBBBBBBKhHhDDk",
      "kHHHHdHBBBBBBLBBLLBLBBLLBBBBBBBBdhHHhhk",
      "kHBBHdBBBBBBBBBBBBBBBBBBBBBBBBBBHdHHhDk",
      ".kHHhdBBBBBBBBBBBBBBBBBBBBBhBBBBBdhhhk.",
      "..kDDiHBBhhBBBBBBBBBBBBBBBBBhBBHHiDkk..",
      "...kdhiBHhBBBBBBBBBBBBBBBBBBDHHhDHDkk..",
      "..dkhHHhDHBBBBBBBBBBBBBBBBBBhDDhBBhdKk.",
      "..kHBBHhdBBBBBBBBBBBBBBBBBBBBdhBBBBHhKk",
      ".kHBBBHhiBBBBBBBHBBBBHBBBBBBBhhHBBBHHhk",
      ".khBBBHdBBBBBBBBHBBBBHBBBBBBBBDhHBBHHhk",
      ".khhhHhhBBBBBBBHBBBBBhBBBBBBBBHDhhHhDk.",
      "..kDDhdDBBhBBBBHBBBBBhBBBBBHBBiDDDKkk..",
      "...kkKhdHHhHBBHhhBBBHhHBBBHhHHdDDKk....",
      "...kDDhDdDhHHBhhDHBHhDHHBHHDddDDhhkd...",
      "..kDhhhhDDdhhHhDiHHHhdhhHHhKDDDDhhhkk..",
      "..khhhhDDDKDDhDDKhHhDkDDhhDKDDDDDDdkk..",
      "..kkdDDDDDdkDDDDkDhhdkDDhDkKkDDkkkk....",
      "....KkkDdkddkDDdRkDDkRkDDkk..kk........",
      "...kkKKKkkKKiiKRRRkkRRRKKRk............",
      "..keBBBBdkKkRRRRRRRRRRRRRRRk...........",
      "..KBBLBBBikRrRRrrrRRrrRRRrRRk..........",
      ".kBLLLLBBBkrRRRrrrrrrrrdrrrrdk.........",
      ".kHBBLBBBHkdRKKRRrrrrrRKrrrHSk.........",
      ".kHBBLBBBHhKKkgkdKKKKkkkRRLsSk.........",
      ".kHBBBBBHHhhDkkDDKKggkggksPPSk.........",
      ".kHBBBBBBBHHhhhhhhKgggggkSPSk..........",
      "..kBBBBBBBHHHHhhhDKggggggkkk...........",
      "..kHHHHHHHHHHHhiDdgggggggkk............",
      "...kDhHHHHHDhhDDDkggggkkkk.............",
      "....kKDhhhDDDDDDkekkddSSk..............",
      "......kkDDDDDDkkeGkkSSSSk..............",
      "........kkkkkkkGwGkkGwwwkk.............",
      "..............drrrekewwGgk.............",
      "..............dprRekRprRGk.............",
      "..............kwwGkkppprGk.............",
      "..............kkkkkkGwwwkk.............",
      "....................kkkkk..............",
      "....................kkkk...............",
    ],
  },
  izquierda: {
    label: "Izquierda",
    faces: "izquierda",
    box: [963, 517, 1124, 782],
    pitch: [4.5, 4.23],
    meanDeltaE: 7.03,
    rows: [
      "............kk......................",
      "..........kkook......kkk............",
      "..........koooKk....kccYk...........",
      "........kKHyOookd..kcccyOk..........",
      ".......kYyyyyyyookdkkYyyOk..........",
      ".......kyyyyyyyyook..kyyOk..........",
      ".......kyyyyyyyyyok..kOyok..........",
      "......kYyykyyyyyyok..Koook..........",
      "......kOsckyyyyyyokkKoooK...........",
      ".....kksRsYyyyyyooKkooook...........",
      "....khDkssscyyyooooKLKkk............",
      "....kHhhkksOOoooooBkkhhKk...........",
      "....kHHhdkkYyOooOkkHhHHhkkk.........",
      "....kHdKhkcccyOkKHHhiiHhkhdk........",
      "....kKDHHkcYYykdHHHippHHkhhhk.......",
      "....KhBBBdhYYBkhHHppppHHkDHhKd......",
      "...kHBBBBHKKKkDhhpppppHHkhHhhk......",
      "...kSBBBBHBBBBBidppPPpHHkhBHhk......",
      "..kBLLBBBBBBBBBBhPPPPPHHkhBBHhk.....",
      ".kBBLBLBBBBBBBBLBHPPPPHHkhBBHDk.....",
      ".iBBBLLBBBBBBLLLLBhPPBhhkhBBHhhk....",
      "kHBBBBBBBLLHBLLLLBhHPhHhhHBBHHhkK...",
      "kBBHBBBiBBBHHBLBBBHHPHHhhHBBHHHDKkk.",
      "kBBHBBHdiBBHHBBBBBHBHHHdhHBBHHHHhDk.",
      "kBhBBBHKBBBHHBBBBBBHBHDDHBBBHhBHHDk.",
      "kHhhBBDSLBBHhHBBBBBBBBBHBBBBBhhhhk..",
      "khhDhHdSSdHHhhBBBBBBBBBBhBBBBHhhk...",
      ".khDDhdSPKhHDhBBBBBBhBBBhHBBBBhkk...",
      ".kiDDihSkkkHDhBBBBBBiHBBBiHBBBBhkK..",
      "..kDDDKSkGkkdhBBBBBBiHBBBiHBBBBHhkK.",
      "...kKhkskkwkdDBBBhHBhBBLLBiBBBBBHHKk",
      "....kDkskkwBLDBBHDDDHBBBBBBBBBBHHhhk",
      ".....kSsdKwPshBHhKDhHBBBHHdBBBHhhhhk",
      ".....kssHdwsDDDdKKKhhHBBHdhHHBHhhDk.",
      ".....kssPHssPSdhHYOKDhHHdDDDhHHhkk..",
      ".....KkssssPSSDhyyYhDDDdDDDDDhhk....",
      ".......ksssSSSDhOYOdDDDDDDDDDDDk....",
      ".......dsssSSKDDkYkDDDDDDDDdDdkK....",
      "........kkkkKdkkkkdDDDDDDDDdkk......",
      ".........kkDPDRRKkDDDDDDDkkk........",
      ".........kKpRRRrRddDDDDkk...........",
      ".........kRrrRrrrRKdddk.............",
      ".........KrrrirrrrdRdk..............",
      "........kprrrirrrrRRRK.....Kkkk.....",
      "........kRrrRHrrrrRDRKk...kHBBHk....",
      "........kKrrRRrrrrRKDgk..dhBBLBHk...",
      ".......kkgkKKiRrrrRkgggk.kBBBLLBHK..",
      ".......kggggkshiiikggggk.kBBBLLBBk..",
      ".......kggggkssssSkggggk.kHBBLLLBk..",
      ".......kggggkSsssSkgggkDkhhBBLBBBk..",
      "........kkgggkSsSkgggkDDDHHHBBBBHk..",
      ".........KkkkkkkkKkkKDDhhhBBBBBBhk..",
      "...........kkSSSSSkkDDDhhHBBBBBhk...",
      "...........kkGsSSgk.kDDDhhHHHHhDk...",
      "..........kkKHwwwwk..kKDDDhhhhDk....",
      ".........kkePpSwwgk...kkDDDDDkK.....",
      ".........kwwpPrrRRk.....kkkkk.......",
      ".........kwwwprRRRk.................",
      ".........kkwwwGGGkk.................",
      "..........kkkkkkkk..................",
    ],
  },
} as const satisfies Record<string, ReferenceSprite>;

// Burbuja con corazón del panel "Detalle (Zoom)" (ΔE medio 7.4).
export const HEART_BUBBLE: readonly string[] = [
  "..KKKKKKKKKK..",
  ".kwwwwwwwwwwk.",
  "KwwwwwwwwwwwwK",
  "KwwwrrwwrrwwwK",
  "KwwrrrrrrrrwwK",
  "KwwrrrrrrrrwwK",
  "KwwwrrrrrrwwwK",
  "KwwwwrrrrwwwwK",
  "KwwwwwrrwwwwwK",
  "KwwwwwwwwwwwwK",
  ".kwwwwwwwwwwk.",
  "..KKKwwwKKKK..",
  "....kwwwK.....",
  "....KwwK......",
  "....KwK.......",
  "....KK........",
];
